-- Migration: Add Regulatory Reporting Module
-- Generated from Prisma schema
-- This is a preview - actual migration will be generated by Prisma

-- Create enum for regulatory report status
CREATE TYPE "RegulatoryReportStatus" AS ENUM (
  'DRAFT',
  'SUBMITTED',
  'IN_PROGRESS',
  'SUCCESS',
  'RULE_ERROR',
  'SYSTEM_ERROR',
  'TIMEOUT_ERROR',
  'REJECTED_BY_UKNF'
);

-- Create enum for regulatory report type
CREATE TYPE "RegulatoryReportType" AS ENUM (
  'QUARTERLY',
  'ANNUAL',
  'AD_HOC',
  'CORRECTION'
);

-- Create RegulatoryReport table
CREATE TABLE "RegulatoryReport" (
  "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  "fileName" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "fileSize" INTEGER NOT NULL,
  "mimeType" TEXT NOT NULL DEFAULT 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  
  -- Metadata
  "entityCode" TEXT NOT NULL,
  "entityName" TEXT NOT NULL,
  "period" TEXT NOT NULL,
  "reportType" "RegulatoryReportType" NOT NULL,
  
  -- Validation & Status
  "status" "RegulatoryReportStatus" NOT NULL DEFAULT 'DRAFT',
  "validatedAt" TIMESTAMP,
  "validationReportUrl" TEXT,
  "validationNotes" TEXT,
  
  -- Submission info
  "submittedById" TEXT NOT NULL,
  "submittedByName" TEXT NOT NULL,
  "submittedByEmail" TEXT NOT NULL,
  "submittedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  
  -- Corrections
  "isCorrection" BOOLEAN NOT NULL DEFAULT FALSE,
  "correctedReportId" TEXT,
  
  -- Archive
  "isArchived" BOOLEAN NOT NULL DEFAULT FALSE,
  "archivedAt" TIMESTAMP,
  
  -- Relations
  "organizationId" TEXT NOT NULL,
  
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT "RegulatoryReport_organizationId_fkey" 
    FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE,
  CONSTRAINT "RegulatoryReport_submittedById_fkey" 
    FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE CASCADE,
  CONSTRAINT "RegulatoryReport_correctedReportId_fkey" 
    FOREIGN KEY ("correctedReportId") REFERENCES "RegulatoryReport"("id") ON DELETE SET NULL
);

-- Create indexes for RegulatoryReport
CREATE INDEX "RegulatoryReport_organizationId_idx" ON "RegulatoryReport"("organizationId");
CREATE INDEX "RegulatoryReport_submittedById_idx" ON "RegulatoryReport"("submittedById");
CREATE INDEX "RegulatoryReport_status_idx" ON "RegulatoryReport"("status");
CREATE INDEX "RegulatoryReport_reportType_idx" ON "RegulatoryReport"("reportType");
CREATE INDEX "RegulatoryReport_period_idx" ON "RegulatoryReport"("period");
CREATE INDEX "RegulatoryReport_isArchived_idx" ON "RegulatoryReport"("isArchived");
CREATE INDEX "RegulatoryReport_correctedReportId_idx" ON "RegulatoryReport"("correctedReportId");
CREATE INDEX "RegulatoryReport_submittedAt_idx" ON "RegulatoryReport"("submittedAt");

-- Create RegulatoryReportComment table
CREATE TABLE "RegulatoryReportComment" (
  "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  "reportId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "userName" TEXT NOT NULL,
  "userRole" "UserRole" NOT NULL,
  "comment" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT "RegulatoryReportComment_reportId_fkey" 
    FOREIGN KEY ("reportId") REFERENCES "RegulatoryReport"("id") ON DELETE CASCADE,
  CONSTRAINT "RegulatoryReportComment_userId_fkey" 
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE
);

-- Create indexes for RegulatoryReportComment
CREATE INDEX "RegulatoryReportComment_reportId_idx" ON "RegulatoryReportComment"("reportId");
CREATE INDEX "RegulatoryReportComment_userId_idx" ON "RegulatoryReportComment"("userId");
CREATE INDEX "RegulatoryReportComment_createdAt_idx" ON "RegulatoryReportComment"("createdAt");

-- Create RegulatoryReportStatusHistory table
CREATE TABLE "RegulatoryReportStatusHistory" (
  "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  "reportId" TEXT NOT NULL,
  "status" "RegulatoryReportStatus" NOT NULL,
  "note" TEXT,
  "changedBy" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT "RegulatoryReportStatusHistory_reportId_fkey" 
    FOREIGN KEY ("reportId") REFERENCES "RegulatoryReport"("id") ON DELETE CASCADE
);

-- Create indexes for RegulatoryReportStatusHistory
CREATE INDEX "RegulatoryReportStatusHistory_reportId_idx" ON "RegulatoryReportStatusHistory"("reportId");
CREATE INDEX "RegulatoryReportStatusHistory_createdAt_idx" ON "RegulatoryReportStatusHistory"("createdAt");

-- Create ReportingCalendar table
CREATE TABLE "ReportingCalendar" (
  "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  "period" TEXT NOT NULL,
  "reportType" "RegulatoryReportType" NOT NULL,
  "dueDate" TIMESTAMP NOT NULL,
  "description" TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "completionRate" DOUBLE PRECISION DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT "ReportingCalendar_period_reportType_unique" 
    UNIQUE ("period", "reportType")
);

-- Create indexes for ReportingCalendar
CREATE INDEX "ReportingCalendar_dueDate_idx" ON "ReportingCalendar"("dueDate");
CREATE INDEX "ReportingCalendar_isActive_idx" ON "ReportingCalendar"("isActive");

-- Add comment to tables (for documentation)
COMMENT ON TABLE "RegulatoryReport" IS 'Regulatory reports submitted by entities';
COMMENT ON TABLE "RegulatoryReportComment" IS 'Communication threads for specific reports';
COMMENT ON TABLE "RegulatoryReportStatusHistory" IS 'Audit trail of status changes';
COMMENT ON TABLE "ReportingCalendar" IS 'Regulatory reporting deadlines and compliance tracking';

-- Sample data for ReportingCalendar (optional)
INSERT INTO "ReportingCalendar" ("period", "reportType", "dueDate", "description", "isActive") VALUES
  ('Q1 2025', 'QUARTERLY', '2025-04-30 23:59:59', 'Sprawozdanie kwartalne za I kwartał 2025 roku', TRUE),
  ('Q2 2025', 'QUARTERLY', '2025-07-31 23:59:59', 'Sprawozdanie kwartalne za II kwartał 2025 roku', TRUE),
  ('Q3 2025', 'QUARTERLY', '2025-10-31 23:59:59', 'Sprawozdanie kwartalne za III kwartał 2025 roku', TRUE),
  ('Q4 2025', 'QUARTERLY', '2026-01-31 23:59:59', 'Sprawozdanie kwartalne za IV kwartał 2025 roku', TRUE),
  ('2024', 'ANNUAL', '2025-03-31 23:59:59', 'Sprawozdanie roczne za rok 2024', TRUE),
  ('2025', 'ANNUAL', '2026-03-31 23:59:59', 'Sprawozdanie roczne za rok 2025', TRUE)
ON CONFLICT DO NOTHING;

-- Grant permissions (adjust based on your setup)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON "RegulatoryReport" TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON "RegulatoryReportComment" TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON "RegulatoryReportStatusHistory" TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON "ReportingCalendar" TO your_app_user;
